apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
    version: canary
  name: app-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: canary
  template:
    metadata:
      labels:
        app: web
        version: canary
    spec:
      containers:
      - image: caddy:2.4.5-alpine
        name: caddy
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 3 
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 2
          timeoutSeconds: 10