apiVersion: v1
kind: Pod
metadata:
  name: support-tier
  labels:
    app: microservices
    tier: support
spec:
  containers:
  - name: counter
    image: lrakai/microservices:counter-v1
    env:
      - name: API_URL
      # DNS for service discovery across namespaces is:
      # <service-name>.<namespace>
        value: "http://app-tier.service-discovery:8080"

  - name: poller
    image: lrakai/microservices:poller-v1
    env:
      - name: API_URL
        # omit namespace to only search in the same namespace
        value: "http://app-tier:$(APP_TIER_SERVICE_PORT)"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
