apiVersion: v1
kind: Pod
metadata:
  name: persist
  namespace: qq3
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - mountPath: /data
      name: redis-storage
  volumes:
  - name: redis-storage
    persistentVolumeClaim:
      claimName: pvc