apiVersion: v1
kind: Pod
metadata:
  labels:
    env: prod
  name: logger
  namespace: blah
spec:
  containers:
  - image: bash
    name: c1
    command: ["/usr/local/bin/bash", "-c"]
    args:
      - ifconfig > /var/log/blah/data;
        sleep 3600;
    volumeMounts:
      - name: vol1
        mountPath: /var/log/blah
  - image: bash
    name: c2
    command: ["/usr/local/bin/bash", "-c"]
    args:
      - sleep 3600;
    volumeMounts:
      - name: vol1
        mountPath: /var/log/blah
  volumes:
    - name: vol1
      hostPath:
        path: /tmp/vol
        type: DirectoryOrCreate
